import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <nav className="flex gap-3">
                    <a href="/" className="p-3 hover:bg-gray-500">
                        홈
                    </a>
                    <a href="/posts" className="p-3 hover:bg-gray-500">
                        게시글 목록
                    </a>
                </nav>
                <div className="p-3">{children}</div>
                <footer>
                    <p>푸터</p>
                </footer>
            </body>
        </html>
    )
}
